# Generated by Django 3.1.1 on 2020-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinfo",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
